# Generated by Django 3.1.2 on 2020-10-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('key', models.BinaryField(max_length=128, null=True)),
                ('had_bought', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=32)),
                ('customer_code', models.IntegerField(editable=False, unique=True)),
                ('introducer_code', models.IntegerField(editable=False)),
            ],
        ),
    ]
