# Generated by Django 3.1.2 on 2020-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(choices=[('reza', 'reza'), ('saeed', 'saeed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='introducer_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
