# Generated by Django 3.1.2 on 2020-10-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201010_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='result_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('result_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('key', models.CharField(max_length=128, null=True)),
                ('had_bought', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(choices=[('saeed', 'saeed'), ('reza', 'reza')], max_length=32)),
                ('customer_code', models.IntegerField(unique=True)),
                ('introducer_code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
