# Generated by Django 3.1.2 on 2020-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201010_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_model',
            name='label',
            field=models.CharField(default='noting_yet', max_length=32),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='created_by',
            field=models.CharField(choices=[('reza', 'reza'), ('saeed', 'saeed')], max_length=32),
        ),
    ]
