# Generated by Django 3.1.2 on 2020-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201010_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user_model',
            name='created_by',
            field=models.CharField(choices=[('saeed', 'saeed'), ('reza', 'reza')], max_length=32),
        ),
    ]
