# Generated by Django 3.1.2 on 2020-10-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201012_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user_model',
            name='url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user_model',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
